-- Copia y pega esto en el Editor SQL de tu Dashboard de Supabase

-- 1. Crear tabla de eventos
CREATE TABLE IF NOT EXISTS public.analytics_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    event_type TEXT NOT NULL, -- ej: 'view_product', 'contact_click', 'download_pdf'
    product_code TEXT,        -- Código del producto (si aplica)
    product_name TEXT,        -- Nombre del producto (para facilitar lectura)
    category TEXT,            -- Categoría del producto
    metadata JSONB DEFAULT '{}'::jsonb -- Datos extra (url, referrer, dispositivo, etc)
);

-- 2. Habilitar RLS (Seguridad)
ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;

-- 3. Crear política para permitir insertar datos públicos (anon)
CREATE POLICY "Permitir inserción pública de eventos"
ON public.analytics_events
FOR INSERT
TO anon, authenticated
WITH CHECK (true);

-- 4. Crear política para que solo el admin/backoffice pueda LEER los datos
-- (Asumiendo que usas service_role o un usuario autenticado específico para el backoffice)
CREATE POLICY "Permitir lectura solo a admins"
ON public.analytics_events
FOR SELECT
TO service_role, authenticated
USING (true); 
-- Ajusta 'authenticated' si tus usuarios normales no deberían ver esto. 
-- Si el backoffice usa la misma app, necesitarás roles. Si es otra app con service_role, esto está bien.

-- 5. Índices para reportes rápidos
CREATE INDEX IF NOT EXISTS idx_analytics_event_type ON public.analytics_events(event_type);
CREATE INDEX IF NOT EXISTS idx_analytics_product_code ON public.analytics_events(product_code);
CREATE INDEX IF NOT EXISTS idx_analytics_created_at ON public.analytics_events(created_at);
